version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: dex_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: tpay
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
  backend:
    build: .
    container_name: dex_backend
    ports:
     - "3000:3000"
    env_file:
      - .env
   # DATABASE_URL: postgres://postgres:password@db:5432/tpay_dex
    depends_on:
      - db